name: CI

on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Run app.py
        run: python app.py
